### ISSUE TITLE
Name Match Bug

### ISSUE THREAD

**Issue by cgreene** [greenelab/iscb-diversity#4]
The name on line 224 of <https://github.com/greenelab/wiki-nationality-estimate/blob/master/data/LSTM_results_keynotes.tsv> is "Ellen Wright Clayton". This individual spoke at the 2011 PSB meeting. Nearly all of the probability for the name goes to CelticEnglish. However, in our plots for PSB 2011, nearly all of the probability appears to go to SouthAsian, which may match the other speaker from that year ("Vijay Pande" - line 223).

**Comment by trang1618** [comment]
There seems to be some discrepancy between that file and https://github.com/greenelab/wiki-nationality-estimate/blob/master/data/LSTM_results_authors.tsv which is where I pulled the predictions from. Here, there is no prediction for "Ellen Wright Clayton", only "Ellen Clayton". Will fix.

**Comment by dhimmel** [comment]
See cell 5 from [this notebook](https://github.com/greenelab/iscb-diversity/blob/60cbc3856ad92818549e029ba8702e117b159fdf/06.combine-names.ipynb):

> ![image](https://user-images.githubusercontent.com/1117703/73138483-f6b6bb80-4030-11ea-9b3c-6a53b9b9a7f4.png)

@arielah is making the predictions from the `full_name` column. However, we cannot directly join this column with `full_name` from `keynotes.tsv` because that full name has middle names, whereas the full names in `full-names.tsv` are created by combining first and last names. So the solution is to use `full-names.tsv` to go from the name in the predictions to first and last names and then to use these two columns jointly when merging keynotes.tsv or other datasets.

Unrelated things that could help simplify things:

- deduplicate `full_name` before making predictions.  `full-names.tsv` has deplucate `full_name` values, so currently our predictions have duplicate names.

- consider deleting the predictions for keynotes.tsv since they're already in `full-names.tsv`.
